### PR TITLE
BR-06-update-supplementary

### PR DESCRIPTION
**Pull request by RespiratoryMicrobiome**
Updating R code related to supplementary results and purging irrelevant files

### CODE REVIEW

**Comment by RespiratoryMicrobiome** [comment]
reviewed and merging

**Comment by RespiratoryMicrobiome** [comment]
reviewed and merging

**Review by mmacaogain — COMMENTED** [review]
reviewed

**Review by mmacaogain — APPROVED** [review]
reviewed and approved.

**Pull request merged**
